"""
Contains dictionaries containing model information for the different agents
"""

# Displacement (dwt), length in ft, speed in knots, endurance in nm

SHIP_MODELS = [{"name": "Zhaotou",
                "#_available": 2,
                "length": 541,
                "displacement": 10000,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 22100
                },

               {"name": "Zhaoduan",
                "#_available": 6,
                "length": 450,
                "displacement": 4000,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 12200
                },

               {"name": "Shuoshi II",
                "#_available": 4,
                "length": 426,
                "displacement": 5800,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 14800
                },

               {"name": "Kanjie",
                "#_available": 1,
                "length": 425,
                "displacement": 5830,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 14800
                },

               {"name": "Dalang I",
                "#_available": 1,
                "length": 370,
                "displacement": 4500,
                "armed": True,
                "max_speed": 28,
                "helicopter": False,
                "endurance": 12300
                },

               {"name": "Type 053",
                "#_available": 3,
                "length": 367,
                "displacement": 2000,
                "armed": True,
                "max_speed": 24,
                "helicopter": False,
                "endurance": 8500
                },

               {"name": "Zhaochang",
                "#_available": 1,
                "length": 360,
                "displacement": 3500,
                "armed": True,
                "max_speed": 24,
                "helicopter": False,
                "endurance": 10700
                },

               {"name": "Zhaoyu",
                "#_available": 1,
                "length": 360,
                "displacement": 3500,
                "armed": True,
                "max_speed": 24,
                "helicopter": False,
                "endurance": 10700
                },

               {"name": "Hai Yang",
                "#_available": 1,
                "length": 345,
                "displacement": 3325,
                "armed": False,
                "max_speed": 24,
                "helicopter": False,
                "endurance": 10300
                },

               {"name": "Zhaojun",
                "#_available": 9,
                "length": 328,
                "displacement": 2700,
                "armed": True,
                "max_speed": 24,
                "helicopter": False,
                "endurance": 9300
                },

               {"name": "Zhaolai",
                "#_available": 4,
                "length": 325,
                "displacement": 4800,
                "armed": False,
                "max_speed": 28,
                "helicopter": False,
                "endurance": 12500
                },

               {"name": "Shucha II",
                "#_available": 10,
                "length": 321,
                "displacement": 4000,
                "armed": True,
                "max_speed": 28,
                "helicopter": False,
                "endurance": 11200
                },

               {"name": "Haixun II",
                "#_available": 1,
                "length": 311,
                "displacement": 1900,
                "armed": True,
                "max_speed": 20,
                "helicopter": False,
                "endurance": 7900
                },

               {"name": "Zhaogao",
                "#_available": 3,
                "length": 308,
                "displacement": 1750,
                "armed": True,
                "max_speed": 20,
                "helicopter": False,
                "endurance": 7600
                },

               {"name": "Jiangdao",
                "#_available": 22,
                "length": 300,
                "displacement": 1500,
                "armed": True,
                "max_speed": 25,
                "helicopter": False,
                "endurance": 3500
                },

               {"name": "Shusheng",
                "#_available": 5,
                "length": 290,
                "displacement": 1750,
                "armed": False,
                "max_speed": 20,
                "helicopter": False,
                "endurance": 7500
                },

               {"name": "Shuwu",
                "#_available": 3,
                "length": 288,
                "displacement": 1750,
                "armed": False,
                "max_speed": 20,
                "helicopter": False,
                "endurance": 7500
                },

               {"name": "Zhaotim",
                "#_available": 15,
                "length": 269,
                "displacement": 1765,
                "armed": True,
                "max_speed": 20,
                "helicopter": False,
                "endurance": 7400
                },

               {"name": "Tuzhong",
                "#_available": 3,
                "length": 278,
                "displacement": 3300,
                "armed": False,
                "max_speed": 16,
                "helicopter": False,
                "endurance": 9800
                },

               {"name": "Shuke",
                "#_available": 3,
                "length": 242,
                "displacement": 1450,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 6800
                },

               {"name": "Shuyou",
                "#_available": 3,
                "length": 242,
                "displacement": 1000,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 6000
                },

               {"name": "Haijian",
                "#_available": 4,
                "length": 230,
                "displacement": 1350,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 6400
                },

               {"name": "Hutao",
                "#_available": 9,
                "length": 223,
                "displacement": 625,
                "armed": True,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5300
                },

               {"name": "Shuzao",
                "#_available": 15,
                "length": 215,
                "displacement": 600,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5200
                },

               {"name": "Haihei",
                "#_available": 2,
                "length": 205,
                "displacement": 450,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4900
                },

               {"name": "Type 618",
                "#_available": 30,
                "length": 201,
                "displacement": 650,
                "armed": True,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5100
                },

               {"name": "Sansha",
                "#_available": 82,
                "length": 196,
                "displacement": 650,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5000
                },

               {"name": "Zongwen",
                "#_available": 1,
                "length": 195,
                "displacement": 850,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5400
                },

               {"name": "Zhongem",
                "#_available": 2,
                "length": 190,
                "displacement": 550,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4900
                },

               {"name": "Haifeng",
                "#_available": 5,
                "length": 190,
                "displacement": 440,
                "armed": True,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4700
                },

               {"name": "non-Spratlys",
                "#_available": 157,
                "length": 184,
                "displacement": 440,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4800
                },

               {"name": "Spratlys",
                "#_available": 234,
                "length": 184,
                "displacement": 500,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4800
                },

               {"name": "Zhongeng",
                "#_available": 10,
                "length": 180,
                "displacement": 1000,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5500
                },

               {"name": "Zhongke",
                "#_available": 6,
                "length": 180,
                "displacement": 500,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4800
                },

               {"name": "Shuoshi",
                "#_available": 1,
                "length": 425,
                "displacement": 5800,
                "armed": False,
                "max_speed": 20,
                "helicopter": True,
                "endurance": 14800
                },

               {"name": "Subian",
                "#_available": 2,
                "length": 370,
                "displacement": 4500,
                "armed": False,
                "max_speed": 20,
                "helicopter": True,
                "endurance": 12000
                },

               {"name": "Haixun I",
                "#_available": 1,
                "length": 310,
                "displacement": 1900,
                "armed": False,
                "max_speed": 18,
                "helicopter": True,
                "endurance": 7900
                },

               {"name": "Shuling",
                "#_available": 1,
                "length": 290,
                "displacement": 1500,
                "armed": False,
                "max_speed": 18,
                "helicopter": True,
                "endurance":7500
                },

               {"name": "Type 630",
                "#_available": 15,
                "length": 211,
                "displacement": 600,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5200
                },

               {"name": "Shuzao I",
                "#_available": 6,
                "length": 201,
                "displacement": 600,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 5200
                },

               {"name": "Shugong",
                "#_available": 1,
                "length": 185,
                "displacement": 525,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4900
                },

               {"name": "Shudi",
                "#_available": 2,
                "length": 182,
                "displacement": 525,
                "armed": False,
                "max_speed": 18,
                "helicopter": False,
                "endurance": 4800
                },


               ]

UAV_MODELS = [{"name": "WLI_GJI",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 20,
               "range": 1250,
               "number_of_airframes": 30},

              {"name": "WLI_WD1",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 0,
               "radius": 11,
               "endurance": 20,
               "range": 1250,
               "number_of_airframes": 45},

              {"name": "BZK-007",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 0,
               "radius": 11,
               "endurance": 16,
               "range": 250,
               "number_of_airframes": 15},

              {"name": "CH-5",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 40,
               "range": 1700,
               "number_of_airframes": 15},

              {"name": "BZK-005",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": False,
               "max_ammunition": 0,
               "radius": 83,
               "endurance": 40,
               "range": 2000,
               "number_of_airframes": 70},

              {"name": "TB-001",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 35,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "WLII",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 32,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "WZ-7",
               "speed": 750,
               "vulnerability": 1,
               "ability_to_target": False,
               "max_ammunition": 0,
               "radius": 83,
               "endurance": 10,
               "range": 2000,
               "number_of_airframes": 20},

              {"name": "WLIII",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 27,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "WZ-10",
               "speed": 750,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 10,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "Y-8",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 10,
               "range": 2000,
               "number_of_airframes": 6},

              {"name": "Y-9",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 20,
               "range": 2000,
               "number_of_airframes": 7}
              ]

SUBMARINE_MODELS = [{'name': 'Kilo',
                     'type': 'Diesel',
                     'visibility': 0,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 6},
                    {'name': 'Ming',
                     'type': 'Diesel',
                     'visibility': 3,
                     'endurance': 40 * 24,
                     'SDR': 9,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 5},
                    {'name': 'Song',
                     'type': 'Diesel',
                     'visibility': 2,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 8},
                    {'name': 'Yuan',
                     'type': 'Diesel',
                     'visibility': 2,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 3},
                    {'name': 'Yuan_1',
                     'type': 'AIP',
                     'visibility': 1,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 11},
                    {'name': 'Yuan_2',
                     'type': 'AIP',
                     'visibility': 0,
                     'endurance': 40 * 24,
                     'SDR': 90,
                     'num_tubes': 6,
                     'max_ammunition': 16,
                     'num_OOB': 8},
                    {'name': 'Shang_1',
                     'type': 'Nuke',
                     'visibility': 2,
                     'endurance': 60 * 24,
                     'SDR': 9,
                     'num_tubes': 6,
                     'max_ammunition': 25,
                     'num_OOB': 2},
                    {'name': 'Shang_2',
                     'type': 'Nuke',
                     'visibility': 1,
                     'endurance': 60 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 25,
                     'num_OOB': 4},
                    {'name': 'Shang_3',
                     'type': 'Nuke',
                     'visibility': 1,
                     'endurance': 60 * 24,
                     'SDR': 45,
                     'num_tubes': 18,
                     'max_ammunition': 25,
                     'num_OOB': 2},
                    {'name': '095',
                     'type': 'Nuke',
                     'visibility': 1,
                     'endurance': 60 * 24,
                     'SDR': 90,
                     'num_tubes': 18,
                     'max_ammunition': 25,
                     'num_OOB': 4},
                    ]
