"""
Contains dictionaries containing model information for the different agents
"""

# Displacement (dwt), length in ft, speed in knots, endurance in nm

SHIP_MODELS = [{"name": "Zhaotou",
                "#_available": 2,
                "length": 541,
                "displacement": 10000,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 22100
                },

               {"name": "Zhaoduan",
                "#_available": 6,
                "length": 450,
                "displacement": 4000,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 12200
                },

               {"name": "Shuoshi II",
                "#_available": 4,
                "length": 426,
                "displacement": 5800,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 14800
                },

               {"name": "Kanjie",
                "#_available": 1,
                "length": 425,
                "displacement": 5830,
                "armed": True,
                "max_speed": 28,
                "helicopter": True,
                "endurance": 14800
                },

               {"name": "Dalang I",
                "#_available": 1,
                "length": 370,
                "displacement": 4500,
                "armed": True,
                "max_speed": 28,
                "helicopter": False,
                "endurance": 12300
                },

               ]

UAV_MODELS = [{"name": "WLI_GJI",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 20,
               "range": 1250,
               "number_of_airframes": 30},

              {"name": "WLI_WD1",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 0,
               "radius": 11,
               "endurance": 20,
               "range": 1250,
               "number_of_airframes": 45},

              {"name": "BZK-007",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 0,
               "radius": 11,
               "endurance": 16,
               "range": 250,
               "number_of_airframes": 15},

              {"name": "CH-5",
               "speed": 210,
               "vulnerability": 3,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 40,
               "range": 1700,
               "number_of_airframes": 15},

              {"name": "BZK-005",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": False,
               "max_ammunition": 0,
               "radius": 83,
               "endurance": 40,
               "range": 2000,
               "number_of_airframes": 70},

              {"name": "TB-001",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 35,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "WLII",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 11,
               "endurance": 32,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "WZ-7",
               "speed": 750,
               "vulnerability": 1,
               "ability_to_target": False,
               "max_ammunition": 0,
               "radius": 83,
               "endurance": 10,
               "range": 2000,
               "number_of_airframes": 20},

              {"name": "WLIII",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 27,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "WZ-10",
               "speed": 750,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 10,
               "range": 2000,
               "number_of_airframes": 15},

              {"name": "Y-8",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 10,
               "range": 2000,
               "number_of_airframes": 6},

              {"name": "Y-9",
               "speed": 210,
               "vulnerability": 2,
               "ability_to_target": True,
               "max_ammunition": 6,
               "radius": 83,
               "endurance": 20,
               "range": 2000,
               "number_of_airframes": 7}
              ]

SUBMARINE_MODELS = [{'name': 'Kilo',
                     'type': 'Diesel',
                     'visibility': 0,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 6},
                    {'name': 'Ming',
                     'type': 'Diesel',
                     'visibility': 3,
                     'endurance': 40 * 24,
                     'SDR': 9,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 5},
                    {'name': 'Song',
                     'type': 'Diesel',
                     'visibility': 2,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 8},
                    {'name': 'Yuan',
                     'type': 'Diesel',
                     'visibility': 2,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 3},
                    {'name': 'Yuan_1',
                     'type': 'AIP',
                     'visibility': 1,
                     'endurance': 40 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 18,
                     'num_OOB': 11},
                    {'name': 'Yuan_2',
                     'type': 'AIP',
                     'visibility': 0,
                     'endurance': 40 * 24,
                     'SDR': 90,
                     'num_tubes': 6,
                     'max_ammunition': 16,
                     'num_OOB': 8},
                    {'name': 'Shang_1',
                     'type': 'Nuke',
                     'visibility': 2,
                     'endurance': 60 * 24,
                     'SDR': 9,
                     'num_tubes': 6,
                     'max_ammunition': 25,
                     'num_OOB': 2},
                    {'name': 'Shang_2',
                     'type': 'Nuke',
                     'visibility': 1,
                     'endurance': 60 * 24,
                     'SDR': 45,
                     'num_tubes': 6,
                     'max_ammunition': 25,
                     'num_OOB': 4},
                    {'name': 'Shang_3',
                     'type': 'Nuke',
                     'visibility': 1,
                     'endurance': 60 * 24,
                     'SDR': 45,
                     'num_tubes': 18,
                     'max_ammunition': 25,
                     'num_OOB': 2},
                    {'name': '095',
                     'type': 'Nuke',
                     'visibility': 1,
                     'endurance': 60 * 24,
                     'SDR': 90,
                     'num_tubes': 18,
                     'max_ammunition': 25,
                     'num_OOB': 4},
                    ]
